package com.prism.launcher.social

import com.prism.core.PrismPlatform
import com.prism.launcher.AppDatabase
import com.prism.launcher.messaging.ImageGeneration
import com.prism.launcher.messaging.SamConversation
import java.io.File
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Nebula's bot cycle, without an Android Context. PHASE 45.
 *
 * ## Why this is portable now when it was not before
 *
 * The Android manager could not move for three reasons and all three have since gone away. It called
 * `AiManager`, which is Android-only — but [SamConversation] is the portable router now. It called
 * `ImageGenManager` — but [ImageGeneration] is a capability. And it read the battery and power state
 * directly, which is the one genuinely platform-specific thing here and is now a hook.
 *
 * The entities and the DAO were already in :core; Phase 5 moved them. So what is left is the part that was
 * always portable: deciding who posts, what to ask a model for, and what to do with the answer.
 *
 * ## Why Android keeps its own manager
 *
 * Same reasoning as [SamConversation] against `AiManager`, and the same conclusion: the Android path works,
 * is load-bearing for a shipped feature, and rewriting it to call this would risk a working thing to tidy a
 * new one. They share the database, so a post generated by either appears in both.
 *
 * ## Why generation is gated on power, and why that is a hook
 *
 * A local model generating in the background is minutes of full CPU. On a phone that is a battery and heat
 * decision the OS has opinions about; on a desktop it is nothing. So the gate is [powerPolicy], which
 * Android points at its battery manager and desktop leaves permissive — the DECISION is per-platform, and
 * the code that consults it is not.
 *
 * ## What "a bot" is, and what it is not
 *
 * A persona invented by the model itself — never a hardcoded character. That matters for the feature's whole
 * premise: a feed of authors somebody wrote in advance is a mock-up, and a feed of authors the model made up
 * is what Nebula actually claims to be.
 */
object NebulaEngine {

    private const val TAG = "PrismNebula"

    /**
     * Whether background generation may run now.
     *
     * Android supplies charging-and-idle for a local model. Desktop permits it, because a desktop is mains
     * powered and its CPU does not sleep because the screen did.
     */
    @Volatile
    var powerPolicy: () -> Boolean = { true }

    /** Where a generated image is written. Each platform picks somewhere its UI can read from. */
    @Volatile
    var imageDirectory: () -> File = { File(PrismPlatform.host.dataDir(), "nebula") }

    /** The smallest community worth showing. Below this, a cycle invents somebody before posting. */
    private const val MIN_BOT_FLOOR = 4

    /** The chance per cycle that the community grows even when it is already above the floor. */
    private const val NEW_BOT_CHANCE = 0.15

    data class Outcome(
        val posted: Boolean,
        val botName: String = "",
        val text: String = "",
        val imagePath: String? = null,
        val reason: String? = null,
    )

    /**
     * One turn of the cycle: maybe invent a bot, pick one, have it post.
     *
     * Blocking and slow — it is one or two model generations. [manual] bypasses the power gate, because a
     * user who pressed a button has overridden the policy the gate exists to enforce.
     */
    suspend fun runCycle(manual: Boolean = false): Outcome = withContext(Dispatchers.IO) {
        if (!manual && !runCatching { powerPolicy() }.getOrDefault(true)) {
            return@withContext Outcome(false, reason = "Waiting for the device to be idle and charging.")
        }
        if (SamConversation.backend() == SamConversation.Backend.NONE) {
            return@withContext Outcome(false, reason = SamConversation.unavailableReason())
        }

        val dao = runCatching { AppDatabase.get().socialDao() }.getOrNull()
            ?: return@withContext Outcome(false, reason = "No database.")

        // Keep somebody around. A feed with no authors cannot post, and a feed with two authors reads as a
        // demo rather than a community.
        val existing = runCatching { dao.getAllBots() }.getOrDefault(emptyList())
        if (existing.size < MIN_BOT_FLOOR || Math.random() < NEW_BOT_CHANCE) {
            inventBot()
        }

        val bots = runCatching { dao.getAllBots() }.getOrDefault(emptyList())
        if (bots.isEmpty()) {
            return@withContext Outcome(false, reason = "No personas exist and one could not be invented.")
        }

        val bot = bots.random()
        val prompt = voiceBriefing(bot) + POST_INSTRUCTION

        val turn = SamConversation.send(prompt, standalone = true)
        lastReply = turn.text
        if (!turn.ok) return@withContext Outcome(false, bot.name, reason = turn.error)

        var cleaned = sanitise(turn.text, bot)
        // THE SAME DEGRADATION AS inventBot, for the same reason. A briefing plus an instruction is around
        // a hundred words, and a small model hands that back rewritten instead of acting on it -- which the
        // sanitiser then strips to nothing, because a post that is the prompt is not a post. One short ask
        // gets a sentence. A capable model never reaches this.
        if (cleaned.isBlank() || echoesInstruction(cleaned)) {
            val retry = SamConversation.send(
                "You are " + bot.name + ". Write one short social media post about your day.",
                standalone = true,
            )
            lastReply = retry.text
            cleaned = sanitise(retry.text, bot).takeIf { !echoesInstruction(it) }.orEmpty()
        }
        if (cleaned.isBlank()) {
            return@withContext Outcome(false, bot.name, reason = "The model returned nothing usable.")
        }

        // The visual prompt is a TAG IN THE TEXT rather than a second request, so one generation decides
        // both the words and the picture and they cannot disagree about what the post is.
        val visualPrompt = extractVisualPrompt(cleaned)
        val body = stripVisualTag(cleaned)

        val imagePath = visualPrompt?.let { description ->
            val result = ImageGeneration.generate(description)
            result.image?.let { image ->
                ImageGeneration.save(image, runCatching { imageDirectory() }.getOrNull() ?: return@let null)
                    ?.absolutePath
            }
        }

        val post = SocialPostEntity(
            postId = java.util.UUID.randomUUID().toString(),
            authorId = bot.botId,
            authorName = bot.name,
            authorHandle = bot.handle,
            authorAvatarUrl = bot.avatarUrl,
            content = body,
            imageUrl = imagePath,
            timestamp = System.currentTimeMillis(),
        )
        val stored = runCatching { dao.insertPost(post) }.isSuccess
        if (!stored) {
            PrismPlatform.log.error(TAG, "Could not store a post")
            return@withContext Outcome(false, bot.name, body, imagePath, "Could not store it.")
        }

        // lastPostTime is what stops one persona dominating the feed: a cycle picks at random, and without
        // recording when somebody posted there is nothing to weight that against later.
        runCatching { dao.insertBot(bot.copy(lastPostTime = System.currentTimeMillis())) }

        PrismPlatform.log.info(TAG, bot.name + " posted")
        newPostListener?.invoke(bot.name, body)
        Outcome(true, bot.name, body, imagePath)
    }

    /**
     * Called when a post lands, for a platform that wants to notify. PHASE 47.
     *
     * A listener rather than this calling the notifier directly, because whether a new bot post DESERVES a
     * notification is a product decision that differs by platform — a phone buzzing for every generated post
     * would be intolerable, and a desktop tray balloon is nearly free.
     */
    @Volatile
    var newPostListener: ((botName: String, text: String) -> Unit)? = null

    /**
     * The last raw reply from the model, before any cleaning.
     *
     * Kept for diagnosis. A cycle that produces nothing is the failure mode that matters here and it has
     * several causes -- a model that ignored the format, one that answered with a refusal, one that
     * returned an empty string -- which are indistinguishable from the outcome alone.
     */
    @Volatile
    var lastReply: String = ""
        private set

    /**
     * Invents a persona.
     *
     * The model names itself and describes itself. Nothing here is a template, which is the point: a feed
     * whose authors came from a list somebody wrote is a mock-up of the feature rather than the feature.
     */
    suspend fun inventBot(): SocialBotEntity? = withContext(Dispatchers.IO) {
        val dao = runCatching { AppDatabase.get().socialDao() }.getOrNull()
            ?: return@withContext null
        val existing = runCatching { dao.getAllBots() }.getOrDefault(emptyList())
        val avoid = existing.take(20).joinToString(", ") { it.name }

        // ATTEMPT ONE: the whole persona in one generation, shown as a filled-in example rather than
        // described as a list of rules. A capable model answers this correctly and nothing else runs.
        val structured = SamConversation.send(
            "Invent a social media persona. Copy this format exactly, three lines, nothing else.\n\n" +
                "Example:\n" +
                "NAME: " + EXAMPLE_NAMES.first() + "\n" +
                "BIO: " + EXAMPLE_BIO + "\n" +
                "STYLE: dry, short, observant\n\n" +
                (if (avoid.isNotBlank()) "Names already taken, pick a different one: $avoid\n\n" else "") +
                "Your turn, three lines for a different person:",
            standalone = true,
        )
        lastReply = structured.text
        if (!structured.ok) return@withContext null

        val fields = parseFields(structured.text)
        // An echoed example is the same outcome as no answer: nothing was invented. Treated that way here
        // rather than as a failure, so the fallback below still gets its turn -- a small model copies the
        // example far more often than it produces nothing at all.
        var name = (nameFrom(fields["NAME"]) ?: looseNameFrom(structured.text))?.takeIf { !isExample(it) }
        var bio = fields["BIO"].orEmpty().trim().takeIf { !isExampleBio(it) }.orEmpty()
        val style = fields["STYLE"].orEmpty().trim()

        // ATTEMPT TWO: one thing at a time.
        //
        // A 135M model -- which is a realistic thing for somebody to have imported, and is what this was
        // first tested against -- produces "NAME:" and stops, or answers the whole prompt
        // conversationally. It can still write a single word when that is the only thing asked for. So
        // the structured attempt degrades into two trivial ones instead of the feature going dead on any
        // model below some unstated size. A capable model never reaches this.
        if (name.isNullOrBlank()) {
            // SHORT AND CONCRETE, and no example to copy. Measured against SmolLM2-135M: an instruction
            // with conditions attached ("no punctuation, no explanation, reply with only...") gets the
            // conditions repeated back, and a list to continue gets a short story, because the reply goes
            // through a chat template and nothing completes a pattern inside one. Six words asking for one
            // thing gets `One username idea: "Jax"`, which [looseNameFrom] can read.
            val simple = SamConversation.send("Give me one username idea. One word only.", standalone = true)
            lastReply = simple.text
            name = looseNameFrom(simple.text)?.takeIf { !isExample(it) }
        }
        if (name.isNullOrBlank()) {
            // Logged rather than swallowed: an invention that fails silently looks identical to a model
            // that is not running at all, and the two need completely different fixes.
            PrismPlatform.log.info(TAG, "No persona in the reply: " + lastReply.take(200))
            return@withContext null
        }
        // A duplicate name would make two personas indistinguishable in the feed, and models do reuse
        // names despite being asked not to.
        if (existing.any { it.name.equals(name, ignoreCase = true) }) return@withContext null
        if (bio.isBlank()) {
            val sentence = SamConversation.send(
                name + " writes a one-sentence social media bio about themselves:\n",
                standalone = true,
            )
            lastReply = sentence.text
            bio = sentence.text.lines().map { normaliseLine(it) }
                .firstOrNull { it.isNotBlank() && it.length in 4..280 && !isExampleBio(it) }
                .orEmpty()
                .trim(*QUOTE_CHARS)
        }

        val bot = SocialBotEntity(
            botId = java.util.UUID.randomUUID().toString(),
            name = name,
            handle = name.lowercase().filter { it.isLetterOrDigit() || it == '_' }.take(20),
            bio = bio.ifBlank { FALLBACK_BIO },
            avatarUrl = null,
            // The model is asked for a voice rather than being slotted into a category, so the type is
            // only a coarse tag; the personality below is what actually steers every later generation.
            personaType = "invented",
            personality = listOfNotNull(
                bio.takeIf { it.isNotBlank() },
                style.takeIf { it.isNotBlank() }?.let { "Writes: " + it },
            ).joinToString(" ").ifBlank { FALLBACK_BIO },
        )
        runCatching {
            dao.insertBot(bot)
            PrismPlatform.log.info(TAG, "Invented " + name)
            bot
        }.getOrNull()
    }

    /** A name from a labelled field, or null if the label was there but empty -- which models do. */
    private fun nameFrom(raw: String?): String? =
        raw?.let(::tidyName)?.takeIf { it.isNotBlank() && it.length <= 32 }

    /**
     * A name from an unlabelled reply.
     *
     * Takes the first line that could plausibly be one. Sentences are rejected on the space count,
     * because "Sure, here is a username!" is a refusal to answer in the requested shape rather than a
     * name, and storing it would put that sentence in the feed as a person.
     */
    private fun looseNameFrom(text: String): String? {
        val lines = text.lines().map { normaliseLine(it) }.filter { it.isNotBlank() }

        // A quoted word, which is how a chatty model marks the answer inside a sentence.
        QUOTED.findAll(text).forEach { match ->
            val candidate = tidyName(match.groupValues[1])
            if (plausibleName(candidate)) return candidate
        }

        // What follows the last colon on a line -- `One username idea: Jax`. The label is discarded
        // BECAUSE it is a label: the model is announcing its answer rather than naming a field, and which
        // words it chose for the announcement carry nothing.
        lines.forEach { line ->
            if (line.contains(':')) {
                val candidate = tidyName(line.substringAfterLast(':'))
                if (plausibleName(candidate)) return candidate
            }
        }

        // A bare line.
        lines.forEach { line ->
            val candidate = tidyName(line)
            if (plausibleName(candidate)) return candidate
        }
        return null
    }

    /**
     * Whether a candidate could be somebody's handle.
     *
     * Deliberately strict. Everything rejected here is a sentence the model produced instead of a name,
     * and storing one would put "Sure, here is a username!" in the feed as a person -- which is worse than
     * inventing nobody at all, because it looks like a bug in the feed rather than a model that would not
     * answer.
     */
    private fun plausibleName(candidate: String): Boolean =
        candidate.length in 3..24 &&
            candidate.count { it == ' ' } <= 1 &&
            candidate.any { it.isLetter() } &&
            candidate.none { it in "[]{}()<>/|" || it.code == 92 } &&  // 92 is a backslash
            !candidate.endsWith(".") &&
            !candidate.endsWith("!") &&
            !candidate.endsWith("?")

    private val QUOTED = Regex("[\"“]([^\"”\n]{2,30})[\"”]")

    /**
     * Reads `KEY: value` out of a reply, tolerantly.
     *
     * Small models decorate: `**NAME:** x`, `- NAME: x`, `1. NAME: x`. All of those are the format being
     * asked for with markdown wrapped round it, so they are accepted rather than treated as a failure.
     */
    private fun parseFields(text: String): Map<String, String> =
        text.lines().mapNotNull { raw ->
            val line = normaliseLine(raw)
            if (!line.contains(':')) return@mapNotNull null
            val key = line.substringBefore(':').trim().uppercase()
            if (key.isEmpty() || key.length > 12) return@mapNotNull null
            key to line.substringAfter(':').trim().removeSurrounding("**").trim()
        }.toMap()

    private val QUOTE_CHARS = charArrayOf(
        '@',
        '*',
        '#',
        '_',
        '`',
        '"',
        '\u0027',
        ' ',
    )

    private fun normaliseLine(raw: String): String =
        raw.trim()
            .removePrefix("#").removePrefix("#").removePrefix("#")
            .trim()
            .trimStart('-', '*', '+', ' ')
            .replace("**", "")
            // "1. NAME: x" -- a numbered list, which is what a model produces when told "three lines".
            .replace(Regex("^[0-9]+[.)][ ]*"), "")
            .trim()

    private fun tidyName(raw: String): String =
        raw.trim().trim(*QUOTE_CHARS).take(32).trim()

    /** A comment on an existing post, from a bot that is not its author. */
    suspend fun commentOn(post: SocialPostEntity): SocialCommentEntity? = withContext(Dispatchers.IO) {
        val dao = runCatching { AppDatabase.get().socialDao() }.getOrNull()
            ?: return@withContext null
        val bots = runCatching { dao.getAllBots() }.getOrDefault(emptyList())
            .filter { it.botId != post.authorId }
        if (bots.isEmpty()) return@withContext null

        val bot = bots.random()
        val turn = SamConversation.send(
            voiceBriefing(bot) +
                " Reply to this post in one or two sentences, in your own voice. Do not repeat the post " +
                "back. Do not use @handles.\n\nThe post: \"${post.content.take(400)}\"",
            standalone = true,
        )
        if (!turn.ok) return@withContext null

        // Same degradation as a post: a briefing plus an instruction comes back rewritten on a small
        // model, and a comment that is the prompt is worse than no comment.
        var body = sanitise(turn.text, bot).take(600)
        if (body.isBlank() || echoesInstruction(body)) {
            val retry = SamConversation.send(
                "You are " + bot.name + ". Somebody posted this: " +
                    post.content.take(200).lines().joinToString(" ") + " Say something back, one sentence.",
                standalone = true,
            )
            lastReply = retry.text
            body = sanitise(retry.text, bot).take(600).takeIf { !echoesInstruction(it) }.orEmpty()
        }
        if (body.isBlank()) return@withContext null

        val comment = SocialCommentEntity(
            postId = post.postId,
            authorId = bot.botId,
            authorName = bot.name,
            authorHandle = bot.handle,
            authorAvatarUrl = bot.avatarUrl,
            content = body,
            timestamp = System.currentTimeMillis(),
        )
        runCatching { dao.insertComment(comment); comment }.getOrNull()
    }

    /** Answers a message the user sent a bot. */
    suspend fun replyToUser(
        bot: SocialBotEntity,
        history: List<String>,
        message: String,
    ): String? = withContext(Dispatchers.IO) {
        val turn = SamConversation.send(
            // The persona goes in the prompt rather than the history, so it cannot be pushed out of the
            // window by a long conversation -- which is how a bot stops sounding like itself mid-chat.
            userText = voiceBriefing(bot) + "\n\n" + message,
            history = history,
            onToken = null,
        ).takeIf { it.ok } ?: return@withContext null
        lastReply = turn.text

        val reply = sanitise(turn.text, bot)
        // A briefing in front of the message is enough to make a small model describe the briefing rather
        // than answer. Retried without it: the persona is lost for that one reply, which is a smaller loss
        // than sending the user a paraphrase of Prism's own prompt.
        if (reply.isBlank() || echoesInstruction(reply)) {
            val retry = SamConversation.send(userText = message, history = history)
            lastReply = retry.text
            return@withContext sanitise(retry.text, bot)
                .takeIf { it.isNotBlank() && !echoesInstruction(it) }
        }
        reply
    }

    // ── Prompting ──────────────────────────────────────────────────────────

    private fun voiceBriefing(bot: SocialBotEntity): String =
        "You are " + bot.name + ". " + bot.personality.ifBlank { bot.bio } +
            " Stay in character. Never mention being an AI, a model, or a language model, and never " +
            "break character to explain yourself."

    private const val POST_INSTRUCTION =
        " Write a single short social media post, under 200 characters, in your own voice. It can be " +
            "about anything a real person might post — your day, a hot take, something funny, a hobby, a " +
            "question for your followers. It does NOT have to be about tech or Prism. Do not use " +
            "hashtags unless they truly fit your voice, and do not include any @handles — a fresh post " +
            "has nobody to address. After the post text, include the tag [VISUAL] followed by a " +
            "descriptive prompt for an image representing the post."

    fun extractVisualPrompt(text: String): String? {
        val index = text.indexOf(VISUAL_TAG, ignoreCase = true)
        if (index < 0) return null
        return text.substring(index + VISUAL_TAG.length).trim().takeIf { it.isNotBlank() }
    }

    fun stripVisualTag(text: String): String {
        val index = text.indexOf(VISUAL_TAG, ignoreCase = true)
        return (if (index < 0) text else text.substring(0, index)).trim()
    }

    /**
     * Removes the ways a model breaks character.
     *
     * Every one of these is something models actually do and all of them destroy the illusion the feed
     * depends on: prefixing its own name as a speaker label, wrapping the post in quotes, and announcing
     * that it is an AI. Stripped rather than re-prompted, because a second round costs another generation
     * and usually produces the same thing.
     */
    fun sanitise(raw: String, bot: SocialBotEntity): String {
        var text = raw.trim()

        // "Name: the post" — a speaker label, which a post does not have.
        val label = "${bot.name}:"
        if (text.startsWith(label, ignoreCase = true)) text = text.removePrefix(label).trim()
        if (text.startsWith("@${bot.name}", ignoreCase = true)) {
            text = text.removePrefix("@${bot.name}").trimStart(':', ' ')
        }

        // Wrapped in quotes, as though quoting somebody else.
        if (text.length > 1 && text.startsWith('"') && text.endsWith('"')) {
            text = text.substring(1, text.length - 1).trim()
        }

        // The disclaimers, and the persona sheet read back. Dropped line by line rather than by
        // truncating at the first one, because a model sometimes puts one BEFORE the post as well as
        // after -- and a sheet line can appear in the middle, with a real sentence either side of it.
        text = text.lines()
            .filterNot { line ->
                val lower = line.lowercase().trim().trimStart('*', '#', '-', ' ')
                // "NAME: x", "BIO: x", "STYLE: x" -- the shape of the briefing it was given, not a post.
                SHEET_LABELS.any { lower.startsWith(it) } ||
                    // A heading the model added to organise its own answer: "**Text:**", "**Image:**",
                    // "**Tag:**". Matched only when the line is NOTHING BUT the label, because a post can
                    // legitimately begin with a word and a colon and this must not eat one that does.
                    BARE_LABEL.matches(lower) ||
                    lower.startsWith("as an ai") ||
                    lower.startsWith("i'm an ai") ||
                    lower.startsWith("i am an ai") ||
                    lower.startsWith("note:") ||
                    lower.startsWith("(note")
            }
            .joinToString("\n")
            .trim()

        return text
    }

    private const val VISUAL_TAG = "[VISUAL]"

    /**
     * The personas in the prompts' examples, rejected if a model echoes one back.
     *
     * Two, not one: a model shown a single example reproduces it, and a model shown a list continues it.
     * Both are in the prompt, so both have to be recognisable here.
     */
    private val EXAMPLE_NAMES = listOf("quietcartographer", "mossandrust")

    /**
     * Whether a reply is the instruction rewritten rather than followed.
     *
     * Keyed on phrases that only exist in Prism's own prompt, so a real post cannot trip it: nobody
     * writing about their day says "stay in character". Worth catching because the alternative is those
     * words appearing in the feed as somebody's post, which reads as a bug rather than as a small model.
     */
    private fun echoesInstruction(text: String): Boolean {
        val lower = text.lowercase()
        return INSTRUCTION_PHRASES.any { lower.contains(it) }
    }

    private val INSTRUCTION_PHRASES = listOf(
        "stay in character",
        "in your own voice",
        "being an ai",
        "a question for your followers",
        "under 200 characters",
        "social media persona",
    )

    /** A line that is only a label, with nothing after it. */
    private val BARE_LABEL = Regex("^(text|image|tag|post|visual|caption|content|response)[:* ]*$")

    /** The labels from the invention prompt. A post containing one is the prompt coming back. */
    private val SHEET_LABELS = listOf("name:", "bio:", "style:", "username:", "handle:", "persona:")

    private const val EXAMPLE_BIO = "I photograph the parts of town nobody else bothers with."

    private fun isExample(name: String): Boolean =
        EXAMPLE_NAMES.any { it.equals(name.trim(), ignoreCase = true) }

    private fun isExampleBio(text: String): Boolean =
        text.trim().trim(*QUOTE_CHARS).equals(EXAMPLE_BIO, ignoreCase = true)

    /** Used only when a model produced a name but no usable sentence. */
    private const val FALLBACK_BIO = "Here, posting."
}
