package com.prism.launcher.language

/**
 * A learner's syllabus: which levels, which lessons, in which order, and how long it will honestly
 * take.
 *
 * ## A lesson is a unit of content, not a sitting
 *
 * This is the one thing to understand about the numbers below, because getting it wrong is how
 * language apps end up lying. The Council of Europe puts A1 at about ninety guided hours. Somebody
 * practising fifteen minutes a day is not finishing A1 in a fortnight, and an app that shows them
 * twenty lessons and implies otherwise has made a promise it cannot keep.
 *
 * So a [PlannedLesson] is one can-do objective — something you could not do before and can do
 * after — and it takes however many sittings it takes. [PlannedLesson.sessions] says how many, up
 * front. The path shows a realistic number of nodes; the estimate underneath it is the real one.
 *
 * ## Nothing here is generated by a model
 *
 * The plan is computed from the framework and the learner's answers, deterministically. That is
 * deliberate: a syllabus that changed every time it was regenerated would not be a syllabus, and a
 * learner is entitled to know that "lesson 7" means the same thing tomorrow as it did today. The
 * model's job starts inside a lesson, not in deciding what the lessons are.
 */
data class LearningPlan(
    val version: Int,
    val generatedAt: Long,
    val targetCode: String,
    val nativeCode: String,
    /** Where the learner starts. Everything below it is marked known, not deleted. */
    val placement: Cefr.Level,
    /** What the plan is aiming at, from the goal they named. */
    val goal: Cefr.Level,
    val levels: List<PlannedLevel>,
    val minutesPerDay: Int,
    /** How hard this pair is, from [LanguageDistance.difficulty]. Shown, not hidden. */
    val difficulty: Double,
    /** True when the target uses a writing system the learner does not already read. */
    val newScript: Boolean,
    /**
     * What the learner said about pace, measured against what the plan actually implies.
     *
     * Present so the app can say something true rather than something encouraging. Someone who
     * picked "1 month" and is starting Japanese from nothing is going to find out eventually; being
     * told at the start, kindly, is the difference between adjusting and quitting.
     */
    val paceNote: String,
) {
    val totalLessons: Int get() = levels.sumOf { it.lessons.size }

    /** Minutes of practice the whole plan implies, from the framework's own hour estimates. */
    val totalMinutes: Int get() = levels.sumOf { it.estimatedMinutes }

    /** Calendar days at the committed daily minutes, assuming the learner actually shows up. */
    val estimatedDays: Int
        get() = if (minutesPerDay <= 0) 0 else Math.ceil(totalMinutes / minutesPerDay.toDouble()).toInt()

    fun level(level: Cefr.Level): PlannedLevel? = levels.firstOrNull { it.level == level }

    /** The first lesson that is neither already known nor done. Where the path opens. */
    fun firstUnfinished(completed: Set<String>): PlannedLesson? =
        levels.filter { !it.alreadyKnown }
            .flatMap { it.lessons }
            .firstOrNull { it.id !in completed }
}

/**
 * @param alreadyKnown true for levels below the learner's placement. They stay on the path and stay
 *        openable: a placement is a guess, and a learner who finds B1 too hard needs to be able to
 *        drop into A2 without being told they have already passed it.
 * @param estimatedMinutes the framework's guided hours for this level, adjusted for the language
 *        pair. Not derived from the lesson count — the lesson count is derived from it.
 */
data class PlannedLevel(
    val level: Cefr.Level,
    val lessons: List<PlannedLesson>,
    val alreadyKnown: Boolean,
    val estimatedMinutes: Int,
)

/**
 * @param objective the can-do statement this lesson exists to deliver, in the learner's own
 *        language. This is what the tutor is told to get them doing.
 * @param topic the subject it is practised through, taken from what the learner said they care
 *        about. The objective is fixed by the framework; the topic is entirely theirs.
 * @param sessions how many sittings at their daily minutes this lesson is expected to take.
 */
data class PlannedLesson(
    val id: String,
    val level: Cefr.Level,
    val index: Int,
    val kind: Cefr.LessonKind,
    val title: String,
    val objective: String,
    val topic: String?,
    val sessions: Int,
)
